### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by mrityuShell** [obheda12/MoneyScope#1]
Hello team , 
I installed the jq but the tool is still not working.

**Comment by obheda12** [comment]
please show the command you used to install jq and the error you are receiving

**Comment by mrityuShell** [comment]
I used ./install.sh , but to be sure I installed on my own too , and when I am giving the command it's showing 
./MoneyScope.sh: line 117: jq: command not found

**Comment by robotshell** [comment]
Try _sudo apt-get install jq_

**Comment by GDATTACKER-RESEARCHER** [comment]
@obheda12 bro can't this tool be edited like that if it can fetch program from a logged in user profile from browser so it can have their private programs in list too?

**Comment by obheda12** [comment]
I may add that functionality late as of now it is only for public
